version: '3.8'

services:
  test_db:
    image: postgres:latest
    container_name: test_container
    environment:
      POSTGRES_USER: ${DB_USER_POS}
      POSTGRES_PASSWORD: ${DB_PASSWORD_POS}
      POSTGRES_DB: ${DB_NAME_POS}
    volumes:
      - test_pg_data:/var/lib/postgresql/data
    ports:
      - '54321:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER_POS} -h localhost -d ${DB_NAME_POS}"]
      start_period: 15s
      interval: 10s
      timeout: 5s
      retries: 3


volumes:
  test_pg_data: