# Generated by Django 5.0.2 on 2024-02-29 19:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '__first__'),
        ('surveys', '0002_alter_answeroption_id_alter_question_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='selected_option',
        ),
        migrations.RemoveField(
            model_name='question',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='question',
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'Survey', 'verbose_name_plural': 'Surveys'},
        ),
        migrations.RemoveField(
            model_name='survey',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='start_date',
        ),
        migrations.AddField(
            model_name='survey',
            name='answer_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_apps.answeroption'),
        ),
        migrations.AddField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_apps.user'),
        ),
        migrations.AddField(
            model_name='survey',
            name='date_started',
            field=models.DateField(blank=True, help_text='День, когда задача должна начаться', null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='deadline',
            field=models.DateField(blank=True, help_text='День, когда задача должна быть выполнена', null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_apps.question'),
        ),
        migrations.AddField(
            model_name='survey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='user_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_apps.userresponse'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(default='Here you can add your description...', max_length=1500, verbose_name='task details'),
        ),
        migrations.DeleteModel(
            name='AnswerOption',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
